import { Team } from "@prisma/client"

// generated by: https://transform.tools/json-to-typescript
// from the response body of curl -X GET http://api.football-data.org/v4/teams?limit=10&offset=0
export interface TeamsRangedQuery {
  count: number
  filters: Filters
  teams: Team[]
}

export interface Filters {
  limit: number
  offset: number
  permission: string
}