// types the resquest for /teams/id
export type TeamRequestParams = {
  id: string
}

export type TeamDataShort = Pick<TeamData, 'name' | 'crest'>

// generated by: https://transform.tools/json-to-typescript
// from the response body of curl -X GET http://api.football-data.org/v4/teams?limit=10&offset=0
export interface TeamsRangedQuery {
  count: number
  filters: Filters
  teams: Team[]
}

export interface Filters {
  limit: number
  offset: number
  permission: string
}

export interface Team {
  id: number
  name: string
  shortName: string
  tla: string
  crest: string
  address: string
  website: string
  founded: number
  clubColors: string
  venue: string
  lastUpdated: string
}
